(function(){
  'use strict';
  const API='https://aura.5.42.122.102.sslip.io';
  const state={route:'projects',filter:'all',query:'',token:localStorage.getItem('noda_web_token')||'',user:null,notes:[],noteId:null,debts:[],files:[],devices:[],deviceId:null,ws:null,wsTimer:null,screen:false,screenW:1,screenH:1,debtPeriod:'all',authReady:false};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=(v)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(v)||0)+' ₽';
  const when=(v,full=false)=>{if(!v)return'—';const d=new Date(v);return new Intl.DateTimeFormat('ru-RU',full?{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'short'}).format(d)};
  const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const routeNames={projects:'Проекты',assistant:'Помощник',files:'Файлы',transfer:'Передача',remote:'Удалённый ПК',terminal:'Терминал',notes:'Заметки',returns:'Возвраты'};
  let toastTimer,noteTimer,recorder,recordChunks=[];

  function toast(message,error=false){const el=$('#toast');el.textContent=message;el.style.borderColor=error?'rgba(255,108,120,.36)':'';el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3600)}
  async function api(path,options={}){const headers={...(options.headers||{})};if(state.token&&!path.startsWith('/auth/'))headers.Authorization=`Bearer ${state.token}`;if(options.body&&!(options.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';let res;try{res=await fetch(API+path,{...options,headers,cache:'no-store'})}catch{throw new Error('Сервер Noda сейчас недоступен')}let data={};try{data=await res.json()}catch{}if(res.status===401&&!path.startsWith('/auth/')){state.token='';state.user=null;localStorage.removeItem('noda_web_token');updateAuthUi()}if(!res.ok)throw new Error(data.error||`Сервер вернул ошибку ${res.status}`);return data}
  function needAuth(){if(state.token&&state.user)return true;openAuth();toast('Сначала войди в Noda');return false}
  function openAuth(){$('#authModal').hidden=false;$('#authError').hidden=true;setTimeout(()=>$('[name=login]',$('#authForm')).focus(),60)}
  function closeModals(){for(const m of $$('.modal-layer'))m.hidden=true}
  function setRoute(route,push=true){if(!routeNames[route])route='projects';state.route=route;if(push&&location.hash!==`#${route}`)history.pushState(null,'',`#${route}`);const links=$$('.nav-link');links.forEach(x=>x.classList.toggle('is-active',x.dataset.route===route));const activeIndex=Math.max(0,links.findIndex(x=>x.dataset.route===route));$('.main-nav').style.setProperty('--active-index',activeIndex);$$('.view').forEach(x=>{const active=x.dataset.view===route;x.hidden=!active;x.classList.toggle('is-active',active)});$('#searchWrap').hidden=!['projects','files','notes','returns'].includes(route);$('#globalSearch').placeholder=route==='projects'?'Поиск по проектам':route==='files'?'Поиск по файлам':route==='notes'?'Поиск по заметкам':'Поиск по возвратам';if(route!=='projects'&&!state.user){openAuth();return}loadRoute(route)}
  function loadRoute(route){if(route==='assistant')loadMessages();if(route==='files')loadFiles();if(route==='notes')loadNotes();if(route==='returns')loadDebts();if(['transfer','remote','terminal'].includes(route)){connectWs();renderDevices()}}

  function projectMark(p){const mark=p.theme?.mark||p.theme?.logo;return mark?`<img src="${esc(mark)}" alt="" onerror="this.remove()">`:p.icon||'<span>•</span>'}
  function projectScreen(p){const src=p.screens?.[0];if(src)return`<img src="${esc(src)}" alt="${esc(p.name)}" loading="lazy">`;const accent=p.accent||'#4d8dff';return`<div style="height:100%;background:radial-gradient(circle at 75% 20%,${accent}55,transparent 32%),linear-gradient(145deg,${p.theme?.bg||'#151b26'},#09111c)"></div>`}
  function renderProjects(){const items=(window.PROJECTS||[]).filter(p=>(state.filter==='all'||p.group===state.filter)&&(!state.query||`${p.name} ${p.category} ${p.tagline}`.toLowerCase().includes(state.query)));$('#projectCount').textContent=`${items.length} ${items.length===1?'проект':'проектов'}`;$('#projectEmpty').hidden=!!items.length;$('#projectGrid').innerHTML=items.map(p=>`<article class="project-card" data-project="${esc(p.id)}" style="--project-accent:${p.accent||'#4d8dff'};--project-bg:${p.theme?.bg||'#151b26'}"><div class="project-tags"><span>${p.group==='work'?'Работа':'Личное'}</span><span>${p.status==='live'?'Работает':'Разработка'}</span></div><div class="project-visual">${projectScreen(p)}</div><div class="project-card-body"><div class="project-mark">${projectMark(p)}</div><div class="project-copy"><strong>${esc(p.name)}</strong><span>${esc(p.tagline||p.category||'')}</span></div><span class="project-open">↗</span></div></article>`).join('');$$('.project-card').forEach(c=>c.onclick=()=>openProject(c.dataset.project))}
  function openProject(id){const p=(window.PROJECTS||[]).find(x=>x.id===id);if(!p)return;$('#drawerBody').innerHTML=`${p.screens?.[0]?`<div class="drawer-hero"><img src="${esc(p.screens[0])}" alt=""></div>`:''}<div class="drawer-brand"><div class="project-mark" style="--project-accent:${p.accent};color:${p.accent}">${projectMark(p)}</div><div><h2>${esc(p.name)}</h2><span>${esc(p.category||'')}</span></div></div><p class="drawer-copy">${esc(p.blurb||p.tagline||'')}</p><div class="drawer-features">${(p.features||[]).slice(0,6).map(f=>`<div class="drawer-feature"><strong>${esc(f.t)}</strong><span>${esc(f.s)}</span></div>`).join('')}</div><div class="drawer-links">${(p.links||[]).map((l,i)=>`<a class="${i===0?'primary-action':'quiet-action'}" href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a>`).join('')}</div>`;$('#projectDrawer').hidden=false}

  function updateAuthUi(){const online=!!state.user;$('#connectionPill').classList.toggle('online',online);$('#connectionPill span').textContent=online?'Noda подключена':'Не подключено';$('#accountName').textContent=state.user?.name||state.user?.email||'Гость';$('#accountState').textContent=online?'Данные синхронизированы':'Войти в Noda'}
  async function verifyAuth(){if(!state.token){state.authReady=true;updateAuthUi();return}try{const d=await api('/me');state.user=d.user;updateAuthUi();connectWs()}catch{state.token='';localStorage.removeItem('noda_web_token');state.user=null;updateAuthUi()}finally{state.authReady=true}}
  async function login(ev){ev.preventDefault();const form=new FormData(ev.currentTarget),error=$('#authError'),submit=$('#authSubmit');const loginValue=String(form.get('login')||'').trim();error.hidden=true;submit.disabled=true;submit.textContent='Подключаю…';state.token='';state.user=null;localStorage.removeItem('noda_web_token');try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({login:loginValue,password:form.get('password')})});state.token=d.token;state.user=d.user;localStorage.setItem('noda_web_token',d.token);closeModals();updateAuthUi();connectWs();loadRoute(state.route);toast('Noda подключена')}catch(e){error.textContent=e.message;error.hidden=false}finally{submit.disabled=false;submit.textContent='Войти'}}
  function logout(){state.token='';state.user=null;localStorage.removeItem('noda_web_token');try{state.ws?.close()}catch{}updateAuthUi();toast('Вы вышли из Noda')}

  async function loadMessages(){if(!needAuth())return;try{const d=await api('/ai/messages');renderMessages(d.messages||[])}catch(e){toast(e.message,true)}}
  function renderMessages(messages){const box=$('#conversation');if(!messages.length){box.innerHTML='<div class="empty-conversation"><div class="noda-orb"><img src="favicon.svg" alt=""></div><strong>Что сделать?</strong></div>';return}box.innerHTML=messages.map(m=>`<div class="message ${m.role==='user'?'user':'assistant'}">${esc(m.content)}</div>`).join('');box.scrollTop=box.scrollHeight;$('.workspace').scrollTop=$('.workspace').scrollHeight}
  async function sendAssistant(ev){ev.preventDefault();if(!needAuth())return;const input=$('#assistantInput'),text=input.value.trim();if(!text)return;input.value='';const box=$('#conversation');if($('.empty-conversation',box))box.innerHTML='';box.insertAdjacentHTML('beforeend',`<div class="message user">${esc(text)}</div><div class="message assistant" id="thinking">Думаю…</div>`);try{const d=await api('/ai/assistant',{method:'POST',body:JSON.stringify({text})});$('#thinking')?.remove();box.insertAdjacentHTML('beforeend',`<div class="message assistant">${esc(d.reply||'Готово.')}</div>`)}catch(e){$('#thinking').textContent=e.message}$('.workspace').scrollTop=$('.workspace').scrollHeight}
  async function toggleRecording(){if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!needAuth())return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());$('#assistantMic').classList.remove('recording');const fd=new FormData();fd.append('file',new Blob(recordChunks,{type:recorder.mimeType||'audio/webm'}),'voice.webm');try{const d=await api('/ai/transcribe',{method:'POST',body:fd});$('#assistantInput').value=d.text||'';$('#assistantInput').focus()}catch(e){toast(e.message,true)}};recorder.start();$('#assistantMic').classList.add('recording')}catch(e){toast('Микрофон недоступен',true)}}

  async function loadFiles(){if(!needAuth())return;try{const d=await api('/files');state.files=d.files||[];renderFiles();await loadTokens()}catch(e){toast(e.message,true)}}
  function renderFiles(){const q=state.query;const files=state.files.filter(f=>!q||f.original_name.toLowerCase().includes(q));$('#filesList').innerHTML=files.length?files.map(f=>`<div class="data-row file-cols"><div class="file-name"><i class="file-icon"><svg viewBox="0 0 24 24"><path d="M5 3h11l3 3v15H5z"/><path d="M15 3v5h4"/></svg></i><span>${esc(f.original_name)}</span></div><span>${esc(deviceName(f.target_token_id)||'Все')}</span><span>${when(f.created_at,true)}</span><span class="status-dot ${f.status==='delivered'?'done':''}">${f.status==='delivered'?'Доставлен':'На сервере'}</span><button class="download-button" data-download="${esc(f.id)}" title="Скачать">↓</button></div>`).join(''):'<div class="empty-inline">Файлов пока нет</div>';$$('[data-download]').forEach(b=>b.onclick=()=>downloadFile(b.dataset.download))}
  async function downloadFile(id){const file=state.files.find(f=>String(f.id)===String(id));try{const res=await fetch(`${API}/files/${encodeURIComponent(id)}/download`,{headers:{Authorization:`Bearer ${state.token}`}});if(!res.ok)throw new Error('Не удалось скачать файл');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=file?.original_name||'download';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){toast(e.message,true)}}
  async function uploadFiles(ev){if(!needAuth())return;const files=[...ev.target.files];for(const file of files){const fd=new FormData();fd.append('file',file);try{await api(`/files${$('#fileTarget').value?`?targetTokenId=${encodeURIComponent($('#fileTarget').value)}`:''}`,{method:'POST',body:fd});toast(`${file.name} загружен`)}catch(e){toast(`${file.name}: ${e.message}`,true)}}ev.target.value='';loadFiles()}
  function deviceKind(d){const hay=`${d.role||''} ${d.name||''} ${d.hostname||''}`.toLowerCase();return d.role==='laptop'||/(laptop|notebook|ноут)/.test(hay)?'laptop':'desktop'}
  function deviceLabel(d){return deviceKind(d)==='laptop'?'Ноутбук':'Компьютер'}
  function deviceIcon(d){return deviceKind(d)==='laptop'?'brand/devices/laptop.png':'brand/devices/desktop.png'}
  function normalizeDevices(list){const groups=new Map();for(const raw of list||[]){const d={...raw,uiKind:deviceKind(raw)};const current=groups.get(d.uiKind);const score=(d.online?1e15:0)+Number(new Date(d.lastSeenAt||d.updated_at||0));const currentScore=current?((current.online?1e15:0)+Number(new Date(current.lastSeenAt||current.updated_at||0))):-1;if(!current||score>currentScore)groups.set(d.uiKind,d)}return['laptop','desktop'].map(k=>groups.get(k)).filter(Boolean)}
  function setDevices(list){state.devices=normalizeDevices(list);if(!state.deviceId||!state.devices.some(x=>String(x.id)===String(state.deviceId)))state.deviceId=state.devices.find(x=>x.online)?.id||state.devices[0]?.id||null;renderDevices()}
  async function loadTokens(){try{const d=await api('/pc/tokens');setDevices(d.tokens||[])}catch{}}
  function deviceName(id){const d=state.devices.find(x=>String(x.id)===String(id));return d?deviceLabel(d):''}
  function selectMeta(select,option){const device=state.devices.find(d=>String(d.id)===String(option.value));return{icon:device?deviceIcon(device):'',hint:device?(device.online?'В сети':'Не в сети'):''}}
  function refreshCustomSelect(select){const root=select.closest('.custom-select');if(!root)return;const current=select.options[select.selectedIndex]||select.options[0],meta=selectMeta(select,current),trigger=$('.select-trigger',root),menu=$('.custom-select-menu',root);trigger.innerHTML=`<span class="select-copy">${meta.icon?`<img src="${meta.icon}" alt="">`:''}<span>${esc(current?.textContent||'Выбрать')}</span></span><svg viewBox="0 0 24 24"><path d="m7 9 5 5 5-5"/></svg>`;menu.innerHTML=[...select.options].map((o,i)=>{const m=selectMeta(select,o);return`<button type="button" class="select-option ${i===select.selectedIndex?'is-selected':''}" data-option-index="${i}">${m.icon?`<img src="${m.icon}" alt="">`:''}<span>${esc(o.textContent)}${m.hint?`<small>${m.hint}</small>`:''}</span></button>`}).join('');$$('.select-option',menu).forEach(b=>b.onclick=()=>{select.selectedIndex=Number(b.dataset.optionIndex);select.dispatchEvent(new Event('change',{bubbles:true}));root.classList.remove('is-open');menu.hidden=true;refreshCustomSelect(select)})}
  function enhanceSelect(select){if(!select||select.dataset.enhanced)return;select.dataset.enhanced='true';const root=document.createElement('div');root.className='custom-select';select.parentNode.insertBefore(root,select);root.appendChild(select);const trigger=document.createElement('button');trigger.type='button';trigger.className='select-trigger';trigger.setAttribute('aria-haspopup','listbox');const menu=document.createElement('div');menu.className='custom-select-menu';menu.hidden=true;root.append(trigger,menu);trigger.onclick=e=>{e.stopPropagation();$$('.custom-select.is-open').forEach(x=>{if(x!==root){x.classList.remove('is-open');$('.custom-select-menu',x).hidden=true}});const open=!root.classList.contains('is-open');root.classList.toggle('is-open',open);menu.hidden=!open};refreshCustomSelect(select)}
  function renderDevices(){for(const sel of [$('#fileTarget'),$('#remoteDevice'),$('#terminalDevice')])if(sel){const first=sel.id==='fileTarget'?'<option value="">Все устройства</option>':'<option value="">Выбрать устройство</option>';const old=sel.value;sel.innerHTML=first+state.devices.map(d=>`<option value="${esc(d.id)}">${deviceLabel(d)}</option>`).join('');sel.value=state.devices.some(d=>String(d.id)===String(old))?old:(state.deviceId||'');enhanceSelect(sel);refreshCustomSelect(sel)}$('#syncDevices').innerHTML=state.devices.length?state.devices.map(d=>`<button class="device-card ${String(d.id)===String(state.deviceId)?'is-active':''}" data-device="${esc(d.id)}"><i><img src="${deviceIcon(d)}" alt=""></i><span><strong>${deviceLabel(d)}</strong><small>${d.online?'В сети':'Не в сети'}</small></span></button>`).join(''):'<div class="empty-inline">Нет подключённых компьютеров</div>';$$('.device-card').forEach(b=>b.onclick=()=>{state.deviceId=b.dataset.device;renderDevices()})}

  function connectWs(){if(!state.token||state.ws?.readyState===1||state.ws?.readyState===0)return;clearTimeout(state.wsTimer);const ws=new WebSocket(API.replace(/^http/,'ws')+`/client?token=${encodeURIComponent(state.token)}`);state.ws=ws;ws.onopen=()=>{ws.send(JSON.stringify({type:'list_devices'}));$('#connectionPill').classList.add('online')};ws.onmessage=ev=>{let m;try{m=JSON.parse(ev.data)}catch{return}handleWs(m)};ws.onclose=()=>{if(state.token){$('#connectionPill').classList.remove('online');state.wsTimer=setTimeout(connectWs,2500)}};ws.onerror=()=>{try{ws.close()}catch{}}}
  function sendPc(message,deviceId=state.deviceId){if(!state.ws||state.ws.readyState!==1){toast('Нет связи с сервером',true);return false}if(!deviceId){toast('Выбери компьютер',true);return false}state.ws.send(JSON.stringify({to:'pc',deviceId,...message}));return true}
  function handleWs(m){if(m.type==='devices'){setDevices(m.devices||[]);return}if(m.type==='pc_offline'){toast('Компьютер не в сети',true);return}if(m.type==='sync_remote_ack'){$('#syncStatusLabel').textContent='В работе';$('#syncStatusTitle').textContent=m.message||'Передача запущена';return}if(m.type==='sync_remote_event'){applySyncEvent(m.event||{});return}if(m.type==='screens'){renderScreens(m.screens||[]);return}if(m.type==='screen_frame'&&m.data){state.screenW=m.w||1;state.screenH=m.h||1;const img=$('#remoteImage');img.src=`data:image/jpeg;base64,${m.data}`;img.hidden=false;$('.remote-empty')?.setAttribute('hidden','');return}if(m.type==='pty_out'){const out=$('#terminalOutput');out.textContent+=m.data||'';out.scrollTop=out.scrollHeight;return}if(m.type==='pty_opened'){$('#terminalOutput').textContent='';return}if(m.type==='pty_exit'){$('#terminalOutput').textContent+='\n[сессия завершена]\n'}}
  function applySyncEvent(e){let pct=0;if(e.type==='phase'){$('#syncStatusLabel').textContent='Подготовка';$('#syncStatusTitle').textContent=e.msg||e.detail||'Проверка'}else if(e.type==='plan'){$('#syncStatusTitle').textContent=`План готов · ${e.files||0} файлов`}else if(e.type==='progress'){pct=e.totalBytes?Math.round((e.bytes||0)/e.totalBytes*100):0;$('#syncStatusLabel').textContent=e.direction==='pull'?'Получение':'Отправка';$('#syncStatusTitle').textContent=e.project||e.file||'Передача';$('#syncSpeed').textContent=formatSpeed(e.speed);$('#syncEta').textContent=e.eta!=null?`${Math.ceil(e.eta)} с`:'—';addSyncEvent(e.project||e.file,e.done&&e.total?`${e.done}/${e.total}`:'')}else if(e.type==='verify'||e.type==='verify_progress'){$('#syncStatusLabel').textContent='Проверка';$('#syncStatusTitle').textContent='Проверяю целостность';pct=e.total?Math.round((e.done||0)/e.total*100):0}else if(e.type==='done'){pct=100;$('#syncStatusLabel').textContent='Готово';$('#syncStatusTitle').textContent=e.msg||'Передача завершена';$('#syncSpeed').textContent='—';$('#syncEta').textContent='0 с';toast('Передача завершена')}else if(e.type==='blocked'||e.type==='error'){$('#syncStatusLabel').textContent='Нужно действие';$('#syncStatusTitle').textContent=e.error||'Передача остановлена';toast(e.error||'Передача остановлена',true)}if(pct){$('#syncProgress').textContent=`${pct}%`;$('#syncProgressBar').style.width=`${pct}%`}}
  function addSyncEvent(name,status){if(!name)return;const tree=$('#syncTree');$('.empty-inline',tree)?.remove();const exists=[...tree.children].find(x=>x.dataset.name===name);if(exists){$('span:last-child',exists).textContent=status;return}tree.insertAdjacentHTML('afterbegin',`<div class="sync-event" data-name="${esc(name)}"><i>✓</i><span>${esc(name)}</span><span>${esc(status)}</span></div>`)}
  function formatSpeed(v){v=Number(v)||0;if(!v)return'—';return v>1048576?`${(v/1048576).toFixed(1)} МБ/с`:`${Math.round(v/1024)} КБ/с`}
  function runSync(mode){if(!needAuth())return;const map={push:'sync_remote_push',pull:'sync_remote_pull',status:'sync_remote_status'};if(sendPc({type:map[mode],reqId:uid()})){$('#syncStatusLabel').textContent='Запуск';$('#syncStatusTitle').textContent=mode==='push'?'Готовлю отправку':mode==='pull'?'Готовлю получение':'Проверяю изменения';$('#syncProgress').textContent='0%';$('#syncProgressBar').style.width='0'}}

  function connectRemote(){const id=$('#remoteDevice').value||state.deviceId;if(!id){toast('Выбери компьютер',true);return}state.deviceId=id;if(!state.screen){sendPc({type:'screen_start',fps:18,quality:76,width:1920},id);sendPc({type:'screen_list'},id);state.screen=true;$('#remoteConnect').textContent='Отключиться'}else{sendPc({type:'screen_stop'},id);state.screen=false;$('#remoteConnect').textContent='Подключиться';$('#remoteImage').hidden=true;$('.remote-empty')?.removeAttribute('hidden')}}
  function renderScreens(screens){$('#screenList').innerHTML=screens.map((s,i)=>`<button class="${i===0?'is-active':''}" data-screen="${esc(s.id)}">${esc(s.name||`Экран ${i+1}`)}</button>`).join('');$$('[data-screen]').forEach(b=>b.onclick=()=>{sendPc({type:'screen_switch',displayId:b.dataset.screen},$('#remoteDevice').value);$$('[data-screen]').forEach(x=>x.classList.toggle('is-active',x===b))})}
  function remotePoint(ev){const img=$('#remoteImage'),r=img.getBoundingClientRect();return{nx:Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),ny:Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))}}
  function remoteInput(action,ev,extra={}){if(!state.screen)return;sendPc({type:'screen_input',action,...remotePoint(ev),...extra},$('#remoteDevice').value)}

  function startTerminal(){const id=$('#terminalDevice').value||state.deviceId;if(!id)return toast('Выбери компьютер',true);state.deviceId=id;sendPc({type:'pty_start',termId:'web',cols:120,rows:32},id)}
  function terminalSend(command){if(!command)return;startTerminal();setTimeout(()=>sendPc({type:'pty_input',termId:'web',data:command+'\r'},$('#terminalDevice').value),120)}

  async function loadNotes(){if(!needAuth())return;try{const d=await api('/notes');state.notes=d.notes||[];if(state.noteId&&!state.notes.some(n=>n.id===state.noteId))state.noteId=null;renderNotes()}catch(e){toast(e.message,true)}}
  function renderNotes(){const q=state.query;const notes=state.notes.filter(n=>!q||`${n.title||''} ${n.body||''}`.toLowerCase().includes(q));$('#notesList').innerHTML=notes.map(n=>`<button class="note-item ${n.id===state.noteId?'is-active':''}" data-note="${n.id}"><strong>${esc(n.title||'Без названия')}</strong><span>${esc((n.body||'').replace(/\s+/g,' ').slice(0,60)||when(n.updated_at,true))}</span></button>`).join('')||'<div class="empty-inline">Нет заметок</div>';$$('.note-item').forEach(b=>b.onclick=()=>selectNote(b.dataset.note));if(state.noteId)fillNote()}
  function selectNote(id){state.noteId=id;renderNotes();fillNote()}
  function fillNote(){const n=state.notes.find(x=>String(x.id)===String(state.noteId));if(!n)return;$('#notePlaceholder').hidden=true;$('#noteFields').hidden=false;$('#noteTitle').value=n.title||'';$('#noteBody').value=n.body||'';$('#noteSaveState').textContent='Сохранено'}
  async function createNote(){if(!needAuth())return;try{const d=await api('/notes',{method:'POST',body:JSON.stringify({title:'',body:''})});state.notes.unshift(d.note);state.noteId=d.note.id;renderNotes();$('#noteTitle').focus()}catch(e){toast(e.message,true)}}
  function scheduleNote(){clearTimeout(noteTimer);$('#noteSaveState').textContent='Сохраняю…';noteTimer=setTimeout(saveNote,600)}
  async function saveNote(){const n=state.notes.find(x=>String(x.id)===String(state.noteId));if(!n)return;const body={title:$('#noteTitle').value,body:$('#noteBody').value,color:n.color};try{const d=await api(`/notes/${n.id}`,{method:'PUT',body:JSON.stringify(body)});Object.assign(n,d.note);$('#noteSaveState').textContent='Сохранено';renderNotes()}catch(e){$('#noteSaveState').textContent='Ошибка';toast(e.message,true)}}
  async function removeNote(){const n=state.notes.find(x=>String(x.id)===String(state.noteId));if(!n)return;if(!confirm('Удалить заметку?'))return;await api(`/notes/${n.id}`,{method:'DELETE'});state.notes=state.notes.filter(x=>x.id!==n.id);state.noteId=null;$('#noteFields').hidden=true;$('#notePlaceholder').hidden=false;renderNotes()}
  async function structureNote(){const text=$('#noteBody').value.trim();if(!text)return;$('#noteSaveState').textContent='Структурирую…';try{const d=await api('/notes/structure',{method:'POST',body:JSON.stringify({text})});const n=state.notes.find(x=>String(x.id)===String(state.noteId));await api(`/notes/${n.id}`,{method:'PUT',body:JSON.stringify({title:$('#noteTitle').value,body:text,structured_body:d.structuredBody,color:n.color})});$('#noteBody').value=d.structuredBody;toast('Версия ИИ создана');scheduleNote()}catch(e){toast(e.message,true)}}

  async function loadDebts(){if(!needAuth())return;try{const d=await api('/debts?all=true');state.debts=d.debts||[];renderDebts()}catch(e){toast(e.message,true)}}
  function debtRecipient(d){const m=String(d.note||'').match(/(?:^|\s)\[(Тима|Даня|Женя)\](?:\s|$)/);return m?.[1]||'Тима'}
  function debtNote(d){return String(d.note||'').replace(/(?:^|\s)\[(Тима|Даня|Женя)\](?:\s|$)/,' ').trim()||'—'}
  function filteredDebts(){const now=new Date(),q=state.query;let from=null;if(state.debtPeriod==='week'){from=new Date(now);from.setDate(now.getDate()-6);from.setHours(0,0,0,0)}if(state.debtPeriod==='month')from=new Date(now.getFullYear(),now.getMonth(),1);return state.debts.filter(d=>(!from||new Date(d.occurred_at||d.created_at)>=from)&&(!q||`${d.counterparty} ${d.note}`.toLowerCase().includes(q))).sort((a,b)=>new Date(b.occurred_at||b.created_at)-new Date(a.occurred_at||a.created_at))}
  const merchantAssets=[[/белка|belka/i,'belkacar.png'],[/сити\s*драйв|city\s*drive/i,'citydrive.ico'],[/делимоб|delimobil/i,'delimobil.png'],[/яндекс/i,'yandex.png'],[/chat\s*gpt|openai/i,'openai.png'],[/ozon|озон/i,'ozon.png'],[/wildberries|вайлдбер/i,'wildberries.png'],[/apple|icloud/i,'apple.ico'],[/google/i,'google.png'],[/telegram/i,'telegram.png'],[/youtube/i,'youtube.png'],[/spotify/i,'spotify.png'],[/билайн|beeline/i,'beeline.png'],[/мегафон/i,'megafon.png']];
  function merchantAsset(d){const text=`${d.counterparty||''} ${debtNote(d)}`;return merchantAssets.find(([re])=>re.test(text))?.[1]||''}
  function debtIcon(d){const asset=merchantAsset(d),letter=esc((debtNote(d)||d.counterparty||'?').trim().slice(0,1).toUpperCase());return asset?`<i class="debt-icon brand-icon"><img src="brand/merchants/${asset}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${letter}</span></i>`:`<i class="debt-icon"><span>${letter}</span></i>`}
  function startOfWeek(date){const d=new Date(date);d.setHours(0,0,0,0);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d}
  function weekLabel(start){const end=new Date(start);end.setDate(start.getDate()+6);const sameMonth=start.getMonth()===end.getMonth();const a=new Intl.DateTimeFormat('ru-RU',sameMonth?{day:'numeric'}:{day:'numeric',month:'short'}).format(start);const b=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(end);return`${a}–${b}`}
  function renderDebts(){const items=filteredDebts(),active=items.filter(d=>!d.settled);$('#debtTotal').textContent=money(active.reduce((s,d)=>s+(d.direction==='i_owe'?-1:1)*Number(d.amount),0));if(!items.length){$('#debtsList').innerHTML='<div class="empty-inline">Записей за период нет</div>';return}const groups=new Map();for(const d of items){const start=startOfWeek(d.occurred_at||d.created_at),key=start.toISOString().slice(0,10);if(!groups.has(key))groups.set(key,{start,items:[]});groups.get(key).items.push(d)}$('#debtsList').innerHTML=[...groups.values()].map(group=>{const groupActive=group.items.filter(d=>!d.settled),groupTotal=groupActive.reduce((s,d)=>s+(d.direction==='i_owe'?-1:1)*Number(d.amount),0);return`<section class="debt-week"><div class="debt-week-head"><i class="week-icon">◫</i><strong>${weekLabel(group.start)}</strong><span>${group.items.length}</span><b>${money(groupTotal)}</b></div>${group.items.map(d=>`<div class="data-row debt-cols ${d.settled?'is-settled':''}"><div class="debt-person">${debtIcon(d)}<strong>${esc(d.counterparty||'Компания')}</strong></div><span>${esc(debtNote(d))}</span><span class="recipient-badge">${esc(debtRecipient(d))}</span><span>${when(d.occurred_at||d.created_at,true)}</span><span class="debt-amount">${money(d.amount)}</span><span class="row-actions"><button class="settle-button" data-settle="${d.id}" title="${d.settled?'Вернуть':'Отметить возвращённым'}">${d.settled?'↺':'✓'}</button><button class="edit-button" data-edit-debt="${d.id}" title="Изменить">•••</button></span></div>`).join('')}</section>`}).join('');$$('[data-settle]').forEach(b=>b.onclick=()=>toggleDebt(b.dataset.settle));$$('[data-edit-debt]').forEach(b=>b.onclick=()=>openDebt(b.dataset.editDebt))}
  function openDebt(id){const d=state.debts.find(x=>String(x.id)===String(id));const f=$('#debtForm');f.reset();f.elements.id.value=d?.id||'';f.elements.counterparty.value=d?.counterparty||'Компания';f.elements.note.value=d?debtNote(d):'';f.elements.recipient.value=d?debtRecipient(d):'Тима';refreshCustomSelect(f.elements.recipient);f.elements.amount.value=d?.amount||'';const dt=d?new Date(d.occurred_at||d.created_at):new Date();dt.setMinutes(dt.getMinutes()-dt.getTimezoneOffset());f.elements.occurred_at.value=dt.toISOString().slice(0,16);$('#debtModalTitle').textContent=d?'Изменить запись':'Новая запись';$('#debtModal').hidden=false}
  async function saveDebt(ev){ev.preventDefault();const fd=new FormData(ev.currentTarget),id=fd.get('id'),body={counterparty:fd.get('counterparty'),note:`[${fd.get('recipient')}] ${fd.get('note')}`.trim(),amount:Number(fd.get('amount')),direction:'owes_me',occurred_at:new Date(fd.get('occurred_at')).toISOString()};try{await api(id?`/debts/${id}`:'/debts',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModals();loadDebts();toast('Сохранено')}catch(e){toast(e.message,true)}}
  async function toggleDebt(id){const d=state.debts.find(x=>String(x.id)===String(id));if(!d)return;await api(`/debts/${id}`,{method:'PATCH',body:JSON.stringify({settled:!d.settled})});loadDebts()}

  function bind(){
    document.addEventListener('click',()=>$$('.custom-select.is-open').forEach(x=>{x.classList.remove('is-open');$('.custom-select-menu',x).hidden=true}));
    $$('[data-route]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();setRoute(x.dataset.route)}));window.addEventListener('popstate',()=>setRoute(location.hash.slice(1)||'projects',false));
    $('#globalSearch').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();if(state.route==='projects')renderProjects();if(state.route==='files')renderFiles();if(state.route==='notes')renderNotes();if(state.route==='returns')renderDebts()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});
    $('#projectFilters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.filter=b.dataset.filter;$$('button',$('#projectFilters')).forEach(x=>x.classList.toggle('is-active',x===b));renderProjects()});
    $$('[data-close-drawer]').forEach(x=>x.onclick=()=>$('#projectDrawer').hidden=true);$('#authButton').onclick=()=>state.user?logout():openAuth();$('#sidebarAuth').onclick=()=>state.user?logout():openAuth();$('#authForm').onsubmit=login;$('#togglePassword').onclick=()=>{const input=$('[name=password]',$('#authForm')),show=input.type==='password';input.type=show?'text':'password';$('#togglePassword').textContent=show?'Скрыть':'Показать';$('#togglePassword').setAttribute('aria-label',show?'Скрыть пароль':'Показать пароль')};$$('[data-close-modal]').forEach(x=>x.onclick=closeModals);
    $('#assistantForm').onsubmit=sendAssistant;$('#assistantMic').onclick=toggleRecording;$('#assistantAttach').onclick=()=>$('#assistantFile').click();$('#assistantInput').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(140,e.target.scrollHeight)+'px'};
    $('#fileUpload').onchange=uploadFiles;$('#refreshFiles').onclick=loadFiles;$$('[data-sync]').forEach(x=>x.onclick=()=>runSync(x.dataset.sync));
    $('#remoteConnect').onclick=connectRemote;$('#remoteDevice').onchange=e=>{state.deviceId=e.target.value;renderDevices()};const img=$('#remoteImage'),canvas=$('#remoteCanvas');img.addEventListener('pointerdown',e=>{canvas.focus();img.setPointerCapture(e.pointerId);remoteInput('down',e)});img.addEventListener('pointermove',e=>{if(e.buttons)remoteInput('move',e)});img.addEventListener('pointerup',e=>remoteInput('up',e));img.addEventListener('dblclick',e=>remoteInput('dbl',e));img.addEventListener('contextmenu',e=>{e.preventDefault();remoteInput('click',e,{button:'right'})});img.addEventListener('wheel',e=>{e.preventDefault();remoteInput('scroll',e,{dy:e.deltaY>0?-120:120})},{passive:false});canvas.addEventListener('keydown',e=>{if(!state.screen)return;e.preventDefault();const special={Enter:'enter',Backspace:'backspace',Escape:'esc',Tab:'tab',ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Delete:'delete',Home:'home',End:'end',' ':'space'};sendPc({type:'screen_input',action:'key',key:special[e.key]||e.key,text:e.key.length===1&&!e.ctrlKey&&!e.altKey?e.key:undefined,ctrl:e.ctrlKey||e.metaKey,alt:e.altKey,shift:e.shiftKey},$('#remoteDevice').value)});
    $('#terminalForm').onsubmit=e=>{e.preventDefault();const v=$('#terminalCommand').value;$('#terminalCommand').value='';terminalSend(v)};$('#terminalDevice').onchange=()=>startTerminal();$$('[data-command]').forEach(b=>b.onclick=()=>terminalSend(b.dataset.command));
    $('#newNote').onclick=createNote;$('#noteTitle').oninput=scheduleNote;$('#noteBody').oninput=scheduleNote;$('#deleteNote').onclick=removeNote;$('#structureNote').onclick=structureNote;
    $('#newDebt').onclick=()=>openDebt();$('#debtForm').onsubmit=saveDebt;enhanceSelect($('[name=recipient]',$('#debtForm')));$('#debtPeriod').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.debtPeriod=b.dataset.period;$$('button',$('#debtPeriod')).forEach(x=>x.classList.toggle('is-active',x===b));renderDebts()};
  }
  bind();renderProjects();(async()=>{await verifyAuth();setRoute(location.hash.slice(1)||'projects',false)})();
})();
