/* ============================================================
   Публичные данные проектов Arra Hub. БЕЗ СЕКРЕТОВ.
   У каждого проекта — СВОЯ светлая бренд-тема (как карточка
   портфолио bembox): карточка и модалка красятся в стиль продукта.
   theme: { bg — подложка «браузера», surface — фон карточки,
            text, dim, border, accent, logo?, mark?, device }
   links — все поверхности проекта (сайт, админка, киоск…).
   screens — реальные скрины (телефонные или браузерные).
   ============================================================ */

// Бренд-иконки (глиф на цветной плитке; currentColor)
var ICN = {
  vpn: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2 4 5.1v5.7c0 4.7 3.4 8.2 8 9.2 4.6-1 8-4.5 8-9.2V5.1z"/></svg>',
  bro: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><rect x="2.5" y="4" width="19" height="13" rx="2"/><path d="M8 20.5h8M12 17v3.5" stroke-linecap="round"/></svg>',
  aura: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l2.4 6.9L21 11l-6.6 2.1L12 20l-2.4-6.9L3 11l6.6-2.1z"/></svg>',
  pad: '<svg viewBox="0 0 24 24" fill="currentColor"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',
  bag: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M5 8h14l-1 12H6z"/><path d="M9 8V6a3 3 0 0 1 6 0v2" stroke-linecap="round"/></svg>',
  locker: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M12 3v18M8 7h.01M16 7h.01" stroke-linecap="round"/></svg>',
  cards: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><rect x="3" y="6" width="14" height="12" rx="2"/><path d="M7 3h11a2 2 0 0 1 2 2v9"/></svg>',
  leaf: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M4 20c0-9 7-16 16-16 0 9-7 16-16 16z"/><path d="M4 20C8 14 12 11 18 9" fill="none" stroke="#fff" stroke-width="1.6" stroke-linecap="round"/></svg>',
  puzzle: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M10 3a2 2 0 0 1 4 0c0 .6.4 1 1 1h3a1 1 0 0 1 1 1v3c0 .6.4 1 1 1a2 2 0 0 1 0 4c-.6 0-1 .4-1 1v3a1 1 0 0 1-1 1h-3a1 1 0 0 1-1-1 2 2 0 0 0-4 0 1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-3c0-.6-.4-1-1-1a2 2 0 0 1 0-4c.6 0 1-.4 1-1V5a1 1 0 0 1 1-1h3a1 1 0 0 0 1-1z"/></svg>',
  book: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M4 5a2 2 0 0 1 2-2h13v16H6a2 2 0 0 0-2 2z"/><path d="M4 5v14"/></svg>',
  pin: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a7 7 0 0 0-7 7c0 5 7 13 7 13s7-8 7-13a7 7 0 0 0-7-7z"/><circle cx="12" cy="9" r="2.5" fill="#fff"/></svg>',
  chart: '<svg viewBox="0 0 24 24" fill="currentColor"><rect x="4" y="12" width="4" height="8" rx="1"/><rect x="10" y="7" width="4" height="13" rx="1"/><rect x="16" y="4" width="4" height="16" rx="1"/></svg>',
  users: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="8" r="3.2"/><path d="M3.5 20a5.5 5.5 0 0 1 11 0"/><path d="M16 5.2a3.2 3.2 0 0 1 0 6M20.5 20a5.5 5.5 0 0 0-4-5.3"/></svg>',
};

var PROJECTS = [
  /* ---------------- Личные (Tima) ---------------- */
  {
    id: "arra-vpn", group: "tima", name: "Arra VPN", category: "Windows-приложение", status: "live", priority: 2,
    accent: "#3C8CE7", icon: ICN.vpn,
    theme: { bg: "#0D1117", surface: "#151C27", text: "#E7ECF5", dim: "#8593A9", border: "#242E3F", accent: "#3C8CE7", mark: "brand/arra-vpn.png", device: "app" },
    tagline: "Личный VPN для Windows на sing-box.",
    blurb: "VLESS Reality, Trojan, Shadowsocks. Split-tunnel по приложениям и доменам, тест-браузер и URL-тест серверов.",
    stack: ["Tauri", "React", "sing-box", "FastAPI"],
    publicUrl: "https://arratima.ru/vpn/", hostingShort: "5.42.102.133 + 83.217.222.28",
    screens: ["screens/arra-vpn/overview.png"],
    links: [
      { label: "Сайт", url: "https://arratima.ru/vpn/", primary: true },
      { label: "Скачать для Windows", url: "https://arratima.ru/download/arra-setup.exe", download: true },
      { label: "Админ-панель", url: "https://arratima.ru/admin/" },
    ],
    previewTitle: "Arra VPN",
    preview: [[{ t: "42 ms", s: "Amsterdam" }, { t: "12", s: "серверов" }], ["chart"], [{ t: "Split by app", s: "91%", glow: true }]],
    features: [
      { t: "Split-tunnel", s: "Только выбранные приложения" },
      { t: "Split по доменам", s: "RU напрямую, остальное — VPN" },
      { t: "Тест-браузер", s: "Изолированный Chrome" },
      { t: "URL-тест", s: "Живость серверов" },
    ],
  },
  {
    id: "arra-bro", group: "tima", name: "Noda", category: "Мобильный и ПК-компаньон", status: "live", priority: 1, featured: true,
    accent: "#F05483", icon: ICN.bro,
    theme: { bg: "#171318", surface: "#21181D", text: "#F7F3F5", dim: "#A99BA2", border: "#39242E", accent: "#F05483", mark: "brand/generated/noda.png", device: "app" },
    tagline: "Телефон, ноутбук, сервер и ПК — один рабочий контур.",
    blurb: "Единый личный помощник вместо прежней Aura: синхронизация проектов через сервер, терминал, файлы, заметки, финансы и удалённый экран. Видно, откуда пришла версия, что изменилось и когда всё обновлялось.",
    stack: ["Electron", "Expo", "React Native", "WebSocket"],
    publicUrl: "", hostingShort: "5.42.122.102 · GitHub Releases",
    screens: ["screens/noda/overview.png"],
    links: [
      { label: "Скачать для Windows", url: "https://github.com/arra123/arra-app/releases/latest", primary: true },
    ],
    previewTitle: "Noda",
    preview: [[{ t: "Ноутбук → сервер", s: "1 352 файла", glow: true }], [{ t: "ПК ← сервер", s: "35 файлов" }, { t: "Codex", s: "YOLO" }], ["line60", "line"]],
    features: [
      { t: "Терминал", s: "Сессии и shell с телефона" },
      { t: "Передача", s: "Push с ноутбука, pull на ПК" },
      { t: "Экран", s: "Удалённый экран и управление" },
      { t: "Файлы и заметки", s: "Передача с телефона и версии ИИ" },
      { t: "Финансы", s: "Траты, долги и распознавание" },
      { t: "Автообновление", s: "GitHub Releases" },
    ],
  },
  {
    id: "macropad", group: "tima", name: "Macropad", category: "Веб-пульт", status: "live", priority: 8,
    accent: "#E64980", icon: ICN.pad,
    theme: { bg: "#140A10", surface: "#1F1119", text: "#F5E3EC", dim: "#A97F92", border: "#372230", accent: "#E64980", mark: "brand/generated/macropad.png", device: "app" },
    tagline: "Пульт-стримдек для рабочих сайтов.",
    blurb: "Synth-панель с кнопками-иконками для быстрого запуска сайтов. Свои кнопки в localStorage.",
    stack: ["HTML/CSS/JS"],
    publicUrl: "https://macropad.5.42.122.102.sslip.io/", hostingShort: "5.42.122.102 · Caddy",
    screens: ["screens/macropad/overview.png"],
    links: [{ label: "Открыть пульт", url: "https://macropad.5.42.122.102.sslip.io/", primary: true }],
    previewTitle: "MACROPAD",
    preview: [[{ t: "◉", s: "home", tag: true }, { t: "◉", s: "sites", tag: true }], [{ t: "bembox" }, { t: "sklad" }, { t: "cards" }], [{ t: "PVZ" }, { t: "+" }]],
    features: [
      { t: "Пульт", s: "Смена режимов в стиле synth" },
      { t: "Кнопки", s: "Запуск сайтов иконками" },
      { t: "Свои сайты", s: "Через localStorage" },
    ],
  },

  /* ---------------- Работа (Work) ---------------- */
  {
    id: "bemapp", group: "work", name: "bembox", category: "Доставка у дома", status: "live", priority: 3, featured: true,
    accent: "#FF7547", icon: ICN.bag,
    theme: { bg: "#FBF6F1", surface: "#FFFFFF", text: "#221B14", dim: "#93857A", border: "#F0E7DE", accent: "#FF7547", logo: "brand/bembox-logo.svg", mark: "brand/bembox-mark.svg", device: "phone" },
    tagline: "Соседская доставка: кофе, вода, продукты. Без звонков, к двери.",
    blurb: "Заказ в один тап. Вход по SMS, оплата ЮKassa, консьерж и админка. Живой сервис в Новой Трёхгорке.",
    stack: ["Next.js 15", "Drizzle", "PostgreSQL"],
    publicUrl: "https://bembox.ru", hostingShort: "5.42.102.133",
    screens: ["screens/bembox/screen-home.webp", "screens/bembox/screen-coffee.webp", "screens/bembox/screen-products.webp"],
    screenLabels: ["Главная и быстрый заказ", "Кофе", "Продукты"],
    links: [
      { label: "Сайт bembox.ru", url: "https://bembox.ru", primary: true },
      { label: "Админка", url: "https://bembox.ru/admin" },
      { label: "Киоск (касса)", url: "https://bembox.ru/kiosk" },
      { label: "Курьер", url: "https://bembox.ru/courier" },
      { label: "Киоск-приложение", url: "https://bembox.ru/kiosk-app" },
    ],
    previewTitle: "bembox.ru",
    preview: [[{ t: "☕ Кофе", s: "15 мин" }, { t: "💧 Вода", s: "19 л" }], [{ t: "Заказ #482", s: "курьер в пути", glow: true }], ["line60", "line"]],
    features: [
      { t: "Заказ в 3 тапа", s: "Кофе, вода, мусор, продукты" },
      { t: "Вход по SMS", s: "OTP через sms.ru" },
      { t: "Консьерж", s: "Чат с напоминаниями" },
      { t: "Оплата", s: "ЮKassa" },
    ],
  },
  {
    id: "bem-box", group: "work", name: "bem.box", category: "Локеры в подъездах", status: "live", priority: 9,
    accent: "#E8590C", icon: ICN.locker,
    theme: { bg: "#FFF3EB", surface: "#FFFFFF", text: "#221408", dim: "#8F7461", border: "#F5DFD0", accent: "#E8590C", mark: "brand/bem-box.png", device: "browser" },
    tagline: "Не постамат — сервис услуг у двери.",
    blurb: "Сеть локеров в подъездах как вход в бытовые услуги: стирка, уборка, посылки. Пока промо-лендинг.",
    stack: ["HTML/CSS/JS", "AI-картинки"],
    publicUrl: "https://bem-box.5.42.122.102.sslip.io/", hostingShort: "5.42.122.102 · Caddy",
    screens: ["screens/bem-box/overview.png"],
    links: [{ label: "Промо-лендинг", url: "https://bem-box.5.42.122.102.sslip.io/", primary: true }],
    previewTitle: "bem.box",
    preview: [[{ t: "Локер 12", s: "в подъезде", glow: true }], [{ t: "Стирка", s: "услуга" }, { t: "bem.box+", s: "подписка" }], ["line40"]],
    features: [
      { t: "Позиционирование", s: "Не постамат, а сервис" },
      { t: "Сценарий", s: "«Постирать вещи»" },
      { t: "Подписка", s: "bem.box+" },
    ],
  },
  {
    id: "cards", group: "work", name: "Генератор карточек", category: "Инструмент", status: "live", priority: 10,
    accent: "#AE3EC9", icon: ICN.cards,
    theme: { bg: "#FAF0FC", surface: "#FFFFFF", text: "#23102A", dim: "#8A6C93", border: "#F0DAF4", accent: "#AE3EC9", mark: "brand/generated/cards.png", device: "app" },
    tagline: "Карточки товаров для WB и Ozon.",
    blurb: "Собирает данные о товаре и генерирует черновик карточки: текст, инфографику, фото, характеристики.",
    stack: ["Node.js", "PostgreSQL", "GPT", "sharp"],
    publicUrl: "https://cards.5.42.122.102.sslip.io/", hostingShort: "5.42.122.102 · systemd",
    screens: ["screens/cards/overview.png"],
    links: [{ label: "Открыть генератор", url: "https://cards.5.42.122.102.sslip.io/", primary: true }],
    previewTitle: "cards",
    preview: [[{ t: "Карточка WB", s: "черновик", glow: true }], ["chart"], [{ t: "SEO", s: "GPT" }, { t: "Фото", s: "без фона" }]],
    features: [
      { t: "Парсер WB", s: "Карточки по артикулам" },
      { t: "SEO-текст", s: "Через GPT" },
      { t: "Фото", s: "Удаление фона" },
    ],
  },
  {
    id: "graflab-eu", group: "work", name: "GRAFLAB Buds EU", category: "Интернет-магазин", status: "live", priority: 11,
    accent: "#2F9E44", icon: ICN.leaf,
    theme: { bg: "#F0FAF2", surface: "#FFFFFF", text: "#0F2413", dim: "#61795F", border: "#DBEFDF", accent: "#2F9E44", mark: "brand/graflab-eu.png", device: "browser" },
    tagline: "EU-магазин премиальных БАДов.",
    blurb: "96 SKU в 11 категориях. Каталог, админка, авторизация, парсер WB, медиа в S3.",
    stack: ["SvelteKit", "Drizzle", "PostgreSQL", "Lucia"],
    publicUrl: "https://graflab.5.42.122.102.sslip.io/", hostingShort: "5.42.122.102 · systemd",
    screens: ["screens/graflab-eu/overview.png"],
    links: [{ label: "Сайт", url: "https://graflab.5.42.122.102.sslip.io/", primary: true }],
    previewTitle: "GRAFLAB Buds EU",
    preview: [[{ t: "96 SKU", s: "11 категорий" }], [{ t: "Longevity", s: "€49" }, { t: "Brain", s: "€39" }], ["line", "line40"]],
    features: [
      { t: "Каталог", s: "96 SKU, 11 категорий" },
      { t: "Авторизация", s: "Lucia + админка" },
      { t: "Парсер WB", s: "Импорт и дедуп" },
    ],
  },
  {
    id: "graflab-ext", group: "work", name: "GRAFLAB Hub", category: "Chrome-расширение", status: "live",
    accent: "#7048E8", icon: ICN.puzzle,
    theme: { bg: "#F3F0FE", surface: "#FFFFFF", text: "#171030", dim: "#6F688C", border: "#E3DCF9", accent: "#7048E8", mark: "brand/graflab-hub-mark.svg", device: "app" },
    tagline: "Авто-логин во все сервисы GRAFLAB.",
    blurb: "Попап со всеми внутренними сайтами, выбор сотрудника и автоматический вход по сохранённым данным.",
    stack: ["Chrome MV3", "Service Worker"],
    publicUrl: "https://extension.5.42.122.102.sslip.io/", hostingShort: "5.42.122.102 · Caddy",
    screens: ["screens/graflab-ext/overview.png"],
    links: [{ label: "Скачать расширение", url: "https://extension.5.42.122.102.sslip.io/graflab-extension.zip", primary: true, download: true }],
    previewTitle: "GRAFLAB Hub",
    preview: [[{ t: "Склад", s: "вход ✓" }, { t: "Сотрудники", s: "авто" }], [{ t: "База знаний", s: "→" }, { t: "Мессенджер", s: "→" }], ["line40"]],
    features: [
      { t: "Хаб", s: "Все сервисы в попапе" },
      { t: "Авто-логин", s: "Service worker" },
      { t: "Аккаунты", s: "Смена с очисткой сессии" },
    ],
  },
  {
    id: "knowledgebase", group: "work", name: "KnowledgeBase", category: "База знаний", status: "live", priority: 4,
    accent: "#137A50", icon: ICN.book,
    theme: { bg: "#F2F9F5", surface: "#FFFFFF", text: "#10261C", dim: "#5B7168", border: "#DCEDE4", accent: "#137A50", mark: "brand/generated/knowledgebase.png", device: "browser" },
    tagline: "Все знания компании в одном месте.",
    blurb: "Документы (TipTap), видео, бизнес-процессы и таблицы. Поиск с русской морфологией, ролевые права.",
    stack: ["React", "Express", "PostgreSQL", "TipTap"],
    publicUrl: "http://147.45.97.155/knowledgeBase/", hostingShort: "147.45.97.155 · PM2",
    screens: ["screens/knowledgebase/home.png", "screens/knowledgebase/documents.png", "screens/knowledgebase/video.png"],
    screenLabels: ["Обзор базы знаний", "Документы и разделы", "Видеоматериалы"],
    links: [{ label: "Открыть базу", url: "http://147.45.97.155/knowledgeBase/", primary: true }],
    previewTitle: "KnowledgeBase",
    preview: [[{ t: "Документы", s: "TipTap", glow: true }], [{ t: "Видео", s: "плейлисты" }, { t: "BPMN", s: "схемы" }], ["line", "line60"]],
    features: [
      { t: "Документы", s: "Секции, версии, backlinks" },
      { t: "Бизнес-процессы", s: "Редактор ReactFlow" },
      { t: "Поиск", s: "Русская морфология" },
      { t: "Права", s: "Ролевые доступы" },
    ],
  },
  {
    id: "pvz", group: "work", name: "PVZ", category: "Аналитика локаций", status: "live", priority: 7,
    accent: "#6658EB", icon: ICN.pin,
    theme: { bg: "#F3F1FF", surface: "#FFFFFF", text: "#171327", dim: "#706A85", border: "#E6E1F7", accent: "#6658EB", mark: "brand/generated/pvz.png", device: "browser" },
    tagline: "Аренда и конкуренты на одной карте.",
    blurb: "Собирает коммерческие помещения, показывает ПВЗ конкурентов, фильтрует площадь и цену и помогает быстро отобрать выгодные локации.",
    stack: ["Node 24", "PostgreSQL", "Playwright", "Leaflet"],
    publicUrl: "https://pvz.5.42.122.102.sslip.io/", hostingShort: "5.42.122.102 · systemd",
    screens: ["screens/pvz/rentals.png", "screens/pvz/map.png", "screens/pvz/best.png"],
    screenLabels: ["Объекты аренды", "Карта конкурентов", "Лучшие локации"],
    links: [{ label: "Карта локаций", url: "https://pvz.5.42.122.102.sslip.io/", primary: true }],
    previewTitle: "PVZ · карта",
    preview: [[{ t: "Топ локация", s: "скор 92", glow: true }], ["chart"], [{ t: "Аренда", s: "1 200 ₽/м²" }, { t: "ПВЗ", s: "4 рядом" }]],
    features: [
      { t: "Парсер ПВЗ", s: "Точки WB по городам" },
      { t: "Аренда", s: "ЦИАН / Avito" },
      { t: "Скоринг", s: "Топ-N локаций" },
    ],
  },
  {
    id: "sklad", group: "work", name: "GRAсклад", category: "Складская система", status: "live", priority: 5,
    accent: "#7C3AED", icon: ICN.chart,
    theme: { bg: "#F6F4FB", surface: "#FFFFFF", text: "#1E1B2E", dim: "#6B6580", border: "#E9E4F5", accent: "#7C3AED", mark: "brand/generated/sklad.png", device: "browser" },
    tagline: "WMS для производства БАДов.",
    blurb: "Стеллажные и паллетные склады, задачи сканирования, упаковка, внутренняя валюта GRAcoin. Интеграции WB/Ozon/CDEK.",
    stack: ["React", "Express", "PostgreSQL", "socket.io"],
    publicUrl: "http://147.45.97.155/sklad", hostingShort: "147.45.97.155 · PM2",
    screens: [
      "screens/sklad/warehouse.png", "screens/sklad/products.png", "screens/sklad/stock.png",
      "screens/sklad/materials.png", "screens/sklad/tasks.png", "screens/sklad/staff.png",
      "screens/sklad/settings.png", "screens/sklad/analytics.png", "screens/sklad/earnings.png",
      "screens/sklad/errors.png", "screens/sklad/fbo.png", "screens/sklad/move.png",
      "screens/sklad/live-monitor.png", "screens/sklad/product-movements.png", "screens/sklad/order-intake.png"
    ],
    screenLabels: [
      "Склады и стеллажи", "Карточки товаров", "Остатки", "Сырьё и материалы", "Задачи",
      "Сотрудники склада", "Настройки", "Аналитика", "Заработок", "Ошибки", "FBO и паллеты",
      "Перемещение", "Мониторинг", "Движение товара", "Приём заказа"
    ],
    links: [{ label: "Открыть склад", url: "http://147.45.97.155/sklad", primary: true }],
    previewTitle: "GRAсклад",
    preview: [[{ t: "Стеллаж A-12", s: "скан ШК", glow: true }], [{ t: "GRAcoin", s: "+15" }, { t: "Упаковка", s: "12 шт" }], ["line60", "line"]],
    features: [
      { t: "Два склада", s: "Стеллажный и паллетный" },
      { t: "Сканирование", s: "Задачи с защитой" },
      { t: "GRAcoin", s: "Валюта за операции" },
      { t: "Интеграции", s: "WB / Ozon / CDEK" },
    ],
  },
  {
    id: "sotrudniki", group: "work", name: "Сотрудники", category: "HR-портал", status: "live", priority: 6,
    accent: "#9333EA", icon: ICN.users,
    theme: { bg: "#F7F3FC", surface: "#FFFFFF", text: "#21162B", dim: "#776A80", border: "#EADFF1", accent: "#9333EA", mark: "brand/generated/sotrudniki.png", device: "browser" },
    tagline: "Управление персоналом и выплатами.",
    blurb: "Структура компании, должности, табель, стажировки, расчёт выплат, отчёты и управление доступами в одном HR-портале.",
    stack: ["React", "Express", "PostgreSQL"],
    publicUrl: "http://147.45.97.155/sotrudniki/", hostingShort: "147.45.97.155 · PM2",
    screens: [
      "screens/sotrudniki/dashboard.png", "screens/sotrudniki/employees.png", "screens/sotrudniki/attendance.png",
      "screens/sotrudniki/positions.png", "screens/sotrudniki/departments.png", "screens/sotrudniki/cabinets.png",
      "screens/sotrudniki/salary.png", "screens/sotrudniki/messages.png", "screens/sotrudniki/daily-reports.png",
      "screens/sotrudniki/directory.png", "screens/sotrudniki/users.png", "screens/sotrudniki/devices.png",
      "screens/sotrudniki/settings.png", "screens/sotrudniki/my-profile.png"
    ],
    screenLabels: [
      "Обзор", "Сотрудники", "Табель", "Должности", "Отделы", "Кабинеты", "Расчёт зарплат",
      "Сообщения", "Ежедневные отчёты", "Справочник должностей", "Пользователи", "Устройства",
      "Настройки", "Мой кабинет"
    ],
    links: [{ label: "Открыть портал", url: "http://147.45.97.155/sotrudniki/", primary: true }],
    previewTitle: "Сотрудники",
    preview: [[{ t: "Зарплата", s: "июль", glow: true }], [{ t: "Табель", s: "QR-чекин" }, { t: "Стажёры", s: "3" }], ["line40", "line"]],
    features: [
      { t: "Карточки", s: "Статусы сотрудников" },
      { t: "Зарплата", s: "Оклад, аванс, бонусы" },
      { t: "Табель", s: "QR-чекины" },
    ],
  },
];
