const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('arra', {
  getStatus: () => ipcRenderer.invoke('get-status'),
  login: (d) => ipcRenderer.invoke('login', d),
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  setMode: (m) => ipcRenderer.invoke('set-mode', m),
  getHistory: () => ipcRenderer.invoke('get-history'),
  api: (method, path, body) => ipcRenderer.invoke('api', { method, path, body }),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  openFile: (p) => ipcRenderer.invoke('open-file', p),
  fsDelete: (p) => ipcRenderer.invoke('fs-delete', p),
  copyPath: (p) => ipcRenderer.invoke('copy-path', p),
  copyText: (t) => ipcRenderer.invoke('copy-path', t),
  // Файлы: превью через main (HEIC и тяжёлые фото), копирование самой картинки/файла
  fileThumb: (path, size) => ipcRenderer.invoke('file-thumb', { path, size }),
  fileInfo: (p) => ipcRenderer.invoke('file-info', p),
  copyImage: (p) => ipcRenderer.invoke('copy-image', p),
  copyFile: (p) => ipcRenderer.invoke('copy-file', p),
  saveImage: (path, dataUrl) => ipcRenderer.invoke('save-image', { path, dataUrl }),
  codexSessions: () => ipcRenderer.invoke('codex-sessions'),
  clipRead: () => ipcRenderer.invoke('clip-read'),
  recopy: (f) => ipcRenderer.invoke('recopy', f),
  logout: () => ipcRenderer.invoke('logout'),
  winMin: () => ipcRenderer.send('win-min'),
  winMax: () => ipcRenderer.send('win-max'),
  winClose: () => ipcRenderer.send('win-close'),
  onStatus: (cb) => ipcRenderer.on('status', (_e, s) => cb(s)),
  onFile: (cb) => ipcRenderer.on('file-received', (_e, f) => cb(f)),
  onFileError: (cb) => ipcRenderer.on('file-error', (_e, e) => cb(e)),
  // Файлы кода / проводник
  term: (msg) => ipcRenderer.send('term', msg),
  onTerm: (cb) => ipcRenderer.on('term-event', (_e, o) => cb(o)),
  getCodeRoot: () => ipcRenderer.invoke('get-code-root'),
  chooseCodeRoot: () => ipcRenderer.invoke('choose-code-root'),
  // Настоящий терминал (PTY) — termId для нескольких вкладок
  ptyStart: (opts) => ipcRenderer.invoke('pty-start', opts),
  ptyInput: (d, termId) => ipcRenderer.send('pty-input', { d, termId }),
  ptyResize: (size, termId) => ipcRenderer.send('pty-resize', { ...size, termId }),
  ptyRestart: (size, termId) => ipcRenderer.send('pty-restart', { ...size, termId }),
  ptyKill: (termId) => ipcRenderer.send('pty-kill', { termId }),
  onPtyData: (cb) => ipcRenderer.on('pty-data', (_e, payload) => cb(payload)),
  onPtyExit: (cb) => ipcRenderer.on('pty-exit', (_e, payload) => cb(payload)),
  onClaudeDone: (cb) => ipcRenderer.on('claude-done', (_e, payload) => cb(payload)),
  notifyAgent: (payload) => ipcRenderer.invoke('agent-notify', payload),
  onFocusTerminal: (cb) => ipcRenderer.on('focus-terminal', (_e, payload) => cb(payload)),
  localVoiceStatus: () => ipcRenderer.invoke('local-voice-status'),
  localVoicePrepare: () => ipcRenderer.invoke('local-voice-prepare'),
  localVoiceTranscribe: (base64) => ipcRenderer.invoke('local-voice-transcribe', { base64 }),
  onLocalVoiceProgress: (cb) => ipcRenderer.on('voice-model-progress', (_e, payload) => cb(payload)),
  // Перенос (синхронизация рабочих файлов с сервером)
  syncRun: (mode, only, role) => ipcRenderer.invoke('sync-run', { mode, only, role }),
  syncCancel: () => ipcRenderer.invoke('sync-cancel'),
  syncBlockers: () => ipcRenderer.invoke('sync-blockers'),
  syncCloseBlockers: (pids) => ipcRenderer.invoke('sync-close-blockers', pids),
  syncForceCloseBlockers: (pids) => ipcRenderer.invoke('sync-force-close-blockers', pids),
  remoteSync: (deviceId, mode) => ipcRenderer.invoke('remote-sync', { deviceId, mode }),
  remoteScreenSend: (deviceId, message) => ipcRenderer.invoke('remote-screen-send', { deviceId, message }),
  onSyncEvent: (cb) => ipcRenderer.on('sync-event', (_e, o) => cb(o)),
  onRemoteSyncEvent: (cb) => ipcRenderer.on('remote-sync-event', (_e, o) => cb(o)),
  onRemoteScreenEvent: (cb) => ipcRenderer.on('remote-screen-event', (_e, o) => cb(o)),
  // Реальный путь перетащенного файла (в Electron 33 File.path удалён → только так)
  filePath: (file) => { try { return webUtils.getPathForFile(file) || ''; } catch { return ''; } },
  // Системные предупреждения (например, запуск от администратора)
  onWarn: (cb) => ipcRenderer.on('app-warn', (_e, m) => cb(m)),
  // Автообновление
  onUpdate: (cb) => ipcRenderer.on('update-event', (_e, o) => cb(o)),
  updateCheck: () => ipcRenderer.invoke('update-check'),
  appVersion: () => ipcRenderer.invoke('app-version'),
  log: (level, source, payload) => ipcRenderer.invoke('app-log', { level, source, payload }),
  openLogs: () => ipcRenderer.invoke('open-logs'),
  logPath: () => ipcRenderer.invoke('log-path'),
  // Голосовой ввод помощника: аудио → текст
  transcribe: (base64, mime) => ipcRenderer.invoke('transcribe', { base64, mime }),
});
